version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_service
    restart: always
    ports:
      - "1883:1883"   # MQTT 標準連接埠
      - "9001:9001"   # WebSocket 連接埠 (選配)
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - mqtt-net

networks:
  mqtt-net:
    driver: bridge